### ISSUE TITLE
Preparing step is failing on a freshly cloned bare repository

### ISSUE THREAD

**Issue by abailly** [ndmitchell/bake#11]
When I start bake from scratch pointing it a freshly cloned bare git repository, it fails in the preparing step with the following odd messages: 

```
Running CI server...
% GIT: Begin gitCheckout
% GIT: Begin gitInitMirror
error: packfile ./objects/pack/pack-4e334e50d18177148e5b9004ede64a2fac19b63a.pack size changed
warning: packfile ./objects/pack/pack-4e334e50d18177148e5b9004ede64a2fac19b63a.pack cannot be accessed
error: packfile ./objects/pack/pack-4e334e50d18177148e5b9004ede64a2fac19b63a.pack size changed
warning: packfile ./objects/pack/pack-4e334e50d18177148e5b9004ede64a2fac19b63a.pack cannot be accessed
error: packfile ./objects/pack/pack-4e334e50d18177148e5b9004ede64a2fac19b63a.pack size changed
warning: packfile ./objects/pack/pack-4e334e50d18177148e5b9004ede64a2fac19b63a.pack cannot be accessed
error: packfile ./objects/pack/pack-4e334e50d18177148e5b9004ede64a2fac19b63a.pack size changed
warning: packfile ./objects/pack/pack-4e334e50d18177148e5b9004ede64a2fac19b63a.pack cannot be accessed
error: packfile ./objects/pack/pack-4e334e50d18177148e5b9004ede64a2fac19b63a.pack size changed
warning: packfile ./objects/pack/pack-4e334e50d18177148e5b9004ede64a2fac19b63a.pack cannot be accessed
error: packfile ./objects/pack/pack-4e334e50d18177148e5b9004ede64a2fac19b63a.pack size changed
warning: packfile ./objects/pack/pack-4e334e50d18177148e5b9004ede64a2fac19b63a.pack cannot be accessed
error: packfile ./objects/pack/pack-4e334e50d18177148e5b9004ede64a2fac19b63a.pack size changed
warning: packfile ./objects/pack/pack-4e334e50d18177148e5b9004ede64a2fac19b63a.pack cannot be accessed
error: packfile ./objects/pack/pack-4e334e50d18177148e5b9004ede64a2fac19b63a.pack size changed
warning: packfile ./objects/pack/pack-4e334e50d18177148e5b9004ede64a2fac19b63a.pack cannot be accessed
error: packfile ./objects/pack/pack-4e334e50d18177148e5b9004ede64a2fac19b63a.pack size changed
warning: packfile ./objects/pack/pack-4e334e50d18177148e5b9004ede64a2fac19b63a.pack cannot be accessed
error: packfile ./objects/pack/pack-4e334e50d18177148e5b9004ede64a2fac19b63a.pack size changed
warning: packfile ./objects/pack/pack-4e334e50d18177148e5b9004ede64a2fac19b63a.pack cannot be accessed
error: packfile ./objects/pack/pack-4e334e50d18177148e5b9004ede64a2fac19b63a.pack size changed
warning: packfile ./objects/pack/pack-4e334e50d18177148e5b9004ede64a2fac19b63a.pack cannot be accessed
error: packfile ./objects/pack/pack-4e334e50d18177148e5b9004ede64a2fac19b63a.pack size changed
warning: packfile ./objects/pack/pack-4e334e50d18177148e5b9004ede64a2fac19b63a.pack cannot be accessed
```

**Comment by ndmitchell** [comment]
Are you using ovenGit or ovenStepGit? When you say "freshly cloned" do you mean one that Bake cloned, or one you cloned for it? Does it happen every time? Did it only start happening after an upgrade?

**Comment by abailly** [comment]
Here is my toplevel `main` function:

```
main :: IO ()
main = do
    putStrLn "Running CI server..."
    let err = "You need to set an environment variable named $REPO for the Git repo"
    repo <- fromMaybe (error err) `fmap` lookupEnv "REPO"
    bake $
      ovenNotifySlack "https://hooks.slack.com/services/xxxx" "#channel" $
      ovenIncremental $
      -- what's this for ? Why the '=' sign...? looks like this is added to patch submitted
      ovenPretty $
      ovenStorePatch $
      ovenGitNotes repo $
      ovenGit repo "master" Nothing $
      ovenNotifyStdout $
      ovenTest (return allTests) execute
      defaultOven{ovenServer=("127.0.0.1",5000)}
```

I have a bare repo that is cloned by the process which configures the host bake is running on, then when `bake server` starts up it mirrors the repo I guess. And yes, it happens every time. When I trigger a `addpatch` things are getting back to normal. 

Here is the latest commit I merged: 7002b84

Thanks,

**Comment by ndmitchell** [comment]
I've just rehabilitated the incremental test using `ovenGit` and it is working. There was a slight niggle that I was no longer exporting `ovenIncremental`, but that was easily fixed. With that, everything worked, so I don't see any `git` issues. Either they don't occur in my test case, or they were fixed in the 250 patches following your point. I suggest you try upgrading to the latest and see if they go away.

**Comment by abailly** [comment]
Sure, will do that and update ticket. Thanks for helping.

**Comment by abailly** [comment]
Hmm, unfortunately, I cannot upgrade easily: newest version requires sqlite, which requires postgres... I am considering working on making the code more independent of the underlying storage mechanism. It seems to me that the main clients of the storage are `Store` and `Stats` so one could imagine: Storing using a simple snapshot of `Cache`, getting stats from pure Haskell code from Cache. Do you think this is feasible? Desirable?

**Comment by ndmitchell** [comment]
There is no requirement for Postgres. The SQLite requires no installed libraries or configured services. I am surprised it is causing you any bother.

**Comment by abailly** [comment]
Here is what I get from `cabal install --only-dependencies`:

```
Building sqlite-simple-0.4.9.0...
Installed sqlite-simple-0.4.9.0
cabal: Error: some packages failed to install:
opaleye-0.3.1.2 depends on postgresql-libpq-0.9.0.2 which failed to install.
postgresql-libpq-0.9.0.2 failed during the configure step. The exception was:
ExitFailure 1
postgresql-simple-0.4.10.0 depends on postgresql-libpq-0.9.0.2 which failed to
install.
```

That said, I would rather not depend on sqlite either as this adds another dependency to the CI machine. The CI is packaged in a docker container but yet... I love bake because it's a simple and efficient engine with no strings attached. If it starts to need an external SQL engine to do its job, I am getting worried. From what I know of your setting I understand you need much more stats than I do but then why not make stats a different service/package? 

Hence if it seems doable and because this is is open-source I am ok to try putting this out of the core engine.

**Comment by ndmitchell** [comment]
That's a development artefact. I'll clean it up in a few hours. Sorry!

The way SQLite is packaged means you should not need to care for Docker. It should be entirely transparent. It has caused zero hassles so far for us. It is far simpler than defining your own file format.

**Comment by abailly** [comment]
OK, so IIUC the Haskell sqlite library knows how to handle sqlite formatted files directly? I thought one would need to rely on installing external library for that... OK, I will wait for your cleanup and give it a try.

**Comment by abailly** [comment]
I incorrectly related the postgres-libpq error to the use of sqlite: my bad. I removed `opaleye` from cabal file and it builds fine.

**Comment by abailly** [comment]
OK, I merged latest changes, removed spurious dependency and CI now works fine. How do I access the stats, now that I have them available :-) ?

**Comment by ndmitchell** [comment]
The Haskell sqlite library has a C file which is the entirety of SQLite as one of its C dependencies, so GHC compiles SQLite into the Haskell library. It makes it very simple. The Opaleye thing is a red herring - I'm currently working with the Opaleye developer to get him to write an SQLite version which will also have no dependency issues, but make all my SQL safer and more flexible. I had accidentally committed the package dependency.

For viewing stats, see https://github.com/ndmitchell/bake#using-the-example, which I just updated. Basically, pass `?stats=` at the end of the URL.

**Comment by abailly** [comment]
Yeah, just discovered all this myself. RTFM :-)

Thanks for the hard work, I would love to lend a hand in this but you are
going very fast...

Le mardi 30 juin 2015, Neil Mitchell <notifications@github.com> a écrit :

> The Haskell sqlite library has a C file which is the entirety of SQLite as
> one of its C dependencies, so GHC compiles SQLite into the Haskell library.
> It makes it very simple. The Opaleye thing is a red herring - I'm currently
> working with the Opaleye developer to get him to write an SQLite version
> which will also have no dependency issues, but make all my SQL safer and
> more flexible. I had accidentally committed the package dependency.
>
> For viewing stats, see
> https://github.com/ndmitchell/bake#using-the-example, which I just
> updated. Basically, pass ?stats= at the end of the URL.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ndmitchell/bake/issues/11#issuecomment-116963023>.
>


-- 
-- 
Arnaud Bailly

twitter: abailly
skype: arnaud-bailly
linkedin: http://fr.linkedin.com/in/arnaudbailly/

**Comment by ndmitchell** [comment]
I only wrote the manual after you asked the question - think of it as user manual on demand. I also wrote some docs on what pretty does given your comment in your example: https://github.com/ndmitchell/bake/blob/master/src/Development/Bake/Pretty.hs#L19

**Comment by abailly** [comment]
OK. Glad to be helpful in some way, then !

-- 
Arnaud Bailly

twitter: abailly
skype: arnaud-bailly
linkedin: http://fr.linkedin.com/in/arnaudbailly/
