### ISSUE TITLE
Checking the length of a hash

### ISSUE THREAD

**Issue by nkaretnikov** [ndmitchell/bake#13]
Two related issues:

1. `README.md` suggests that `bake addpatch --name=cb3c2a71` should work, but it doesn't because a hash must be 40 chars long (see `sha1`  in `src/Development/Bake/Git.hs`).

2. I can't find a way to retry a patch. If I pass a 40 char hash to `addpatch`, `rowPatch` in `src/Development/Bake/Server/Web.hs` will prepend a quote to it, so the hash will fail the 40 char check in `sha1`. After that I had to clean all bake files because it failed to start.

Error messages:

```
Output: bake-test: SHA1 for Git must be 40 characters long, got "'ec1b02295770352e9f4c8ff2b675b1ada898f896"

bake-test: user error (Pattern match failure in do expression at src/Development/Bake/Server/Store.hs:116:9-98)
```

Steps to reproduce (in the bake source dir):

```
terminal1$ REPO=$(pwd) dist/build/bake-test/bake-test server
terminal2$ REPO=$(pwd) dist/build/bake-test/bake-test client
terminal3$ dist/build/bake-test/bake-test addpatch --name=$(git rev-parse HEAD)
```

I've tried changing both `sha1` and `rowPatch`, but neither seems to work.  Unfortunately, I have to give up on this for today, but here are the patches.  Not sure whether either is a good idea, so I'm just putting them here.

```
commit 3ad1d26314fb534bb1347658036015b9a525b65d
Author: Nikita Karetnikov <nikita@karetnikov.org>
Date:   Thu Jul 9 18:32:09 2015 +0300

    Do not prepend a quote to a hash on retry
    
    This causes bake to fail because it expects a hash to be 40 characters
    long.

diff --git a/src/Development/Bake/Server/Web.hs b/src/Development/Bake/Server/Web.hs
index 8d75f27..4b068d1 100644
--- a/src/Development/Bake/Server/Web.hs
+++ b/src/Development/Bake/Server/Web.hs
@@ -334,7 +334,7 @@ rowPatch Shower{..} mem@Memory{..} argsAdmin info = (code, [showTime time, state
                 if paAlive pi then
                     do br_; admin (DelPatch p) $ str_ "Delete"
                 else if isNothing $ paMerge pi then
-                    do br_; admin (AddPatch (paAuthor pi) $ toPatch $ '\'' : fromPatch p) $ str_ "Retry"
+                    do br_; admin (AddPatch (paAuthor pi) p) $ str_ "Retry"
                 else
                     mempty
             | otherwise = mempty
```

```
commit a173edc71188ded5dada2c8dfe61e55daf05c021
Author: Nikita Karetnikov <nikita@karetnikov.org>
Date:   Thu Jul 9 18:50:34 2015 +0300

    Do not check the length of a hash

diff --git a/src/Development/Bake/Git.hs b/src/Development/Bake/Git.hs
index 24f739c..a4c30f5 100644
--- a/src/Development/Bake/Git.hs
+++ b/src/Development/Bake/Git.hs
@@ -24,8 +24,9 @@ import Prelude
 newtype SHA1 = SHA1 {fromSHA1 :: String} deriving (Show,Eq)
 
 sha1 :: String -> SHA1
-sha1 x | length x /= 40 = error $ "SHA1 for Git must be 40 characters long, got " ++ show x
-       | not $ all (`elem` "0123456789abcdef") x = error $ "SHA1 for Git must be all lower case hex, got " ++ show x 
+sha1 x | not $ all (`elem` "0123456789abcdef'") x =
+           error $ "SHA1 for Git must be all lower case hex " ++
+                   "or a quote character ('), got " ++ show x
        | otherwise = SHA1 x
 
 instance Stringy SHA1 where
```

**Comment by ndmitchell** [comment]
Thanks for the report.

1) I am expecting all git SHA1's to be the full 40 element hash, and expecting that if people want short SHA1 options they will do it themselves as a wrapper script on top. In my implementation we have something that resolves using `git rev-parse`, defaulting to `HEAD` if nothing is specified. I could allow shorter hashes, but I'd prefer to always work with full hashes in the app and shorter hashes outside. That said, I'm on the fence as to whether to allow shorter hashes or not.

2) Retry doesn't work for identical patch names, so I prepend a `'` to them. Using the `ovenPretty` helper you write something like `neil=ccc...` (where `neil` is the branch name), and then retry makes it `'neil=ccc...`, which is still valid. Dropping leading `'` from the sha1 seems like the right thing to do.

So both of these could be fixed, and the second almost certainly should, but both are easily worked around.

**Comment by ndmitchell** [comment]
I changed the docs, and your code in #17 and #18 fixed the other, so this is all now sorted.
