### ISSUE TITLE
retry adds an ' character to existing SHA which is not a valid SHA1

### ISSUE THREAD

**Issue by amarpotghan** [ndmitchell/bake#17]

**Comment by ndmitchell** [comment]
Thanks for the patch in #18, very useful!

It definitely worked, although it violated the invariant that `stringyFrom` and `stringyTo` should form an isomorphism. I'm not sure if that's actually important to Bake or not (my guess is not in this instance), but it's a useful property to have, so I've refactored in such a way that the number of primes are also stored .

**Comment by amarpotghan** [comment]
Thanks :+1:
