### ISSUE TITLE
Client crashes due to error 500 when finishing

### ISSUE THREAD

**Issue by abailly** [ndmitchell/bake#22]
I got the following recurring error with bake:

     Running CI
     -- Client start ------------------------------------------------------
     Client: client1
     Id: 1
     Test: Prepare
     State: 2c0d93c48129252d146ad78b88ada05a1ebbd0d1
     Patches:
     ----------------------------------------------------------------------

     -- Client stop -------------------------------------------------------
     Client: client1
     Id: 1
     Result: Success
     Duration: 2.61s
     ----------------------------------------------------------------------

     -- Client start ------------------------------------------------------
     Client: client1
     Id: 2
     Test: Dependencies
     State: 2c0d93c48129252d146ad78b88ada05a1ebbd0d1
     Patches:
     ----------------------------------------------------------------------

     -- Client stop -------------------------------------------------------
     Client: client1
     Id: 2
     Result: Success
     Duration: 3.15s
     ----------------------------------------------------------------------

     -- Client start ------------------------------------------------------
     Client: client1
     Id: 3
     Test: Compile
     State: 2c0d93c48129252d146ad78b88ada05a1ebbd0d1
     Patches:
     ----------------------------------------------------------------------

     -- Client stop -------------------------------------------------------
     Client: client1
     Id: 3
     Result: Success
     Duration: 24m13s
     ----------------------------------------------------------------------

     ci: Incorrect code: ((5,0,0),"Internal Server Error ","http://server:5000/api/finish")
     "endOfInput"

**Comment by ndmitchell** [comment]
Did it start happening recently? Did you recently upgrade?

**Comment by abailly** [comment]
Yes. It seems to happen since 8f88f49.

-- 
Arnaud Bailly

twitter: abailly
skype: arnaud-bailly
linkedin: http://fr.linkedin.com/in/arnaudbailly/

**Comment by ndmitchell** [comment]
Can you roll back to b8689a319ab4e5ae86f3dfc48bcd6ff4bafb1839 while I have a think.

**Comment by ndmitchell** [comment]
Pro tip: Never read a file lazily then delete it. Should be now fixed.

**Comment by abailly** [comment]
Thanks :-) Was just reverting to b8689a3...

**Comment by ndmitchell** [comment]
What I don't quite understand is how the tests still passed. I guess the Text library must grab one chunk of buffer initially, so small files still work? Although I don't quite believe that.

**Comment by abailly** [comment]
I think that might be the case actually, because initial tests are actually "cached" so output is very small. There might be some race conditions at work here.

**Comment by ndmitchell** [comment]
That certainly sounds plausible. I can't see such pre-buffering in either bake or the text package, but it may be happening in the GHC handle reading code itself.

**Comment by abailly** [comment]
I still encounter same issue after merging 66a5e99. I enabled verbose logging in server and I can see the test result being received but client receives error 500:

```
ci: Incorrect code: ((5,0,0),"Internal Server Error ","http://server:5000/api/finish")
"endOfInput"
```

Any idea?

**Comment by ndmitchell** [comment]
Any idea what hash you were at before that failed? Have you upgraded Wai/Warp etc in the meantime? My server is running fine with the latest code.

**Comment by abailly** [comment]
Sorry for late answer: 
* no clear idea, Amar merged your changes to get fixes on retry but last time I merged was around 0.3 I think
* I did not upgrade anything, just build with `cabal install --only-deps` then `cabal build`

I will try to bisect to get to failure point

**Comment by ndmitchell** [comment]
If you are able to bisect that would be great - I have no idea what could be going wrong. My best plan is to rewrite the finish streaming stuff (so we can stream bigger files, and upload multiple files after a run) and hope that it goes away with that - at the very least we'll get better features and avoid lazy IO (which seems a plausible candidate for the message you are seeing).

**Comment by ndmitchell** [comment]
I just pushed a very big update that stops using JSON for sending finished messages and switches to multipart chunked HTTP messages. Given the massive difference in the code, I suggest trying the current HEAD and see if it has gone away, or is giving a different error message.

**Comment by abailly** [comment]
Looks like it's fixed now. Thanks a lot for the hard work.

**Comment by ndmitchell** [comment]
Thanks for all the testing!
