### ISSUE TITLE
Build output disappears 

### ISSUE THREAD

**Issue by abailly** [ndmitchell/bake#27]
It seems that after a day build output disappears. When I click on patch/state link in admin I got the odd message: 

    bake-store/state-2/extra-long.html: openFile: does not exist (No such file or directory)

When I try to go back in time and retrieve link, it does not work either.

**Comment by ndmitchell** [comment]
That shouldn't be the case - everything should be stored forever... It should also be robust to the file having been deleted.

**Comment by ndmitchell** [comment]
Are the error messages always of the form `extra-long.html`? Any chance you are running some garbage collecting process, other than the one Bake provides? Are you running the built in `bake gc`?

**Comment by abailly** [comment]
You are right: we are running our own clean-up process which removes all bake files! Apologies for the noise...
