### ISSUE TITLE
Bring up clients as needed? (assuming clients are virtualized)

### ISSUE THREAD

**Issue by lierdakil** [ndmitchell/bake#35]
Couldn't find an answer either in the docs or in the source (admittedly, didn't read too much into latter)

Let's imagine a scenario. I have a Haskell project that I want to test against multiple GHC versions. I also have a beefy server I can use for that. So I create multiple containers for each GHC version I want to test against, and set up bake client in each of those. For the sake of simplicity, let's assume I run bake server on host itself.

Now, I don't want to have containers running 24/7, but only when there's a build to do (assume that those start almost instantaneously compared to build time, so almost no overhead there). So, the question is, is there a way to bring up client instances on demand? (e.g. by shelling out some IO commands from server)

**Comment by ndmitchell** [comment]
So it all depends on how long bringing up a container really takes, and if you need to keep a container around for multiple tests in series (e.g. does one test step compile, while a second test step executes). If it really is cheap, you can just have your test action bring up the container, run whatever action it needs, then take down the container. Any reason not to do that?

The other question is why not have these containers running all the time? When they aren't doing anything their overhead will basically be zero CPU and a bit of RAM which will get swapped out to disk anyway. If you were hosting these on a paid provider (e.g. AWS) I could see a strong reason for wanting to take them down, but not necessarily on your own box.

**Comment by lierdakil** [comment]
I never specified that it was my own box. What I meant by 'I have' is 'I have access to'. That said, this is more of a curiosity question at this point, since leaving containers running is an option. So I'm just probing for architectural possibilities here.

Do you mean I could bring up containers in `ovenPrepare`, or in actual test action? Correct me if I'm wrong, but I assumed test code is run on client instance, which means that in order to actually run a test, client has to be up and running? Then I would have to run all clients on host as well, and that seems a little bit... odd? I'm a bit unclear about pipeline here, so forgive me if these questions are somewhat stupid.

Putting containers down is not as much of an issue, since it's always possible to bring a container down if it's idling by an auxiliary tool or even from within a container. It's bringing those up is what I'm confused about at the moment.

As for actual cost of bringing containers up, think "seconds", not "minutes".

**Comment by ndmitchell** [comment]
So there are two places you could imagine bringing up a container, either on the server side or the client side. On the server side you could imagine that if there are no clients available of a particular type, you run some IO action. On the client side, you could create a fake client (perhaps indeed running on the server) that if necessary spawns a container and forwards to it. I guess on the server would be cleaner.

So no, Bake doesn't support anything like that, but you could imagine it doing so, if there was desire.

**Comment by lierdakil** [comment]
Okay then, I'll see if I can hack that in. One last question, while we're at it. If there are literally no clients running, and there comes a test request, do tests wait for client instances or do they instantly fail in this case?

**Comment by abailly** [comment]
IIRC they are queued until a client becomes available. This is the same mechanism than if you run out of clients while more patches are coming on.

**Comment by ndmitchell** [comment]
@abaily is right - requests can queue up indefinitely.

**Comment by lierdakil** [comment]
Ok, great. Thank you for your answers.
