### ISSUE TITLE
Build failure with extra-1.5.1

### ISSUE THREAD

**Issue by DanBurton** [ndmitchell/bake#40]
As seen on the stackage build server, building `bake-0.4`:

```
[ 4 of 26] Compiling General.Extra    ( src/General/Extra.hs, dist/build/General/Extra.o )

src/General/Extra.hs:16:5: error:
    Ambiguous occurrence ‘eitherToMaybe’
    It could refer to either ‘Data.Either.Extra.eitherToMaybe’,
                             imported from ‘Data.Either.Extra’ at src/General/Extra.hs:45:1-24
                          or ‘General.Extra.eitherToMaybe’,
                             defined at src/General/Extra.hs:116:1
```

**Comment by ndmitchell** [comment]
Thanks. I've just released bake-0.5 which fixes these issues. If that's going to cause any issues with stackage LTS not moving forward with extra (I suspect it will?) please just drop bake from Stackage (I'm not convinced it's stable and supported enough to belong there at the moment).
