### ISSUE TITLE
How to handle multiple branches?

### ISSUE THREAD

**Issue by abailly** [ndmitchell/bake#9]
We would like our bake server to be able to handle multiple git branches with different workflows. Is it possible already and if so, what would be the best way to do that?

**Comment by ndmitchell** [comment]
Are these branches all part of the same project? How do the workflows differ? How do you want Bake to treat them differently? In the extreme, one approach is just to run two instances of Bake and keep them entirely isolated.

**Comment by abailly** [comment]
(apologies for late answer, I was travelling...)
yes, these are all braches in the same project. The idea is that we would have:
* one `review` branch that contains changes to be reviewed and deployed. When this build passes it is automatically merged to `master` then deployed locally and to dockerhub for later deployment to production
* zero or more `testing-XXX` branches that would be only deployed locally (with different parameters than main branch) 

Thinking about it, I wonder if I could not simply generate different `[Test]` in the `ovenPrepare` step according to the branch I am in. But this implies I would need to have some information about the branch I am currently building which does not seem available...

I though about running different instances of the server but then this would imply having instances of client for each server, right?

**Comment by ndmitchell** [comment]
Since Bake merges branches together when testing, having testing and review branches with different tests, and that get merged differently, is unlikely to work. If there was no branch merging then that could be made to work, but is fairly different to the typical bake workflow.

Having different instances would require different clients at the moment. However, that's not absolutely essential - if all the clients were compiled into the same binary (which seems the easiest way) then the only thing they need to share is the number of threads they can commit, and how many are already committed. With that information, and some fairly small reworking of the Bake client, they could poll the available servers and serve work for any of them.

**Comment by abailly** [comment]
(apologies again, not very reactive on this...)

IIUC, the merging is done through `ovenUpdateState` function which is currently implemented mainly in `ovenGit`. There is nothing preventing me from overriding this behaviour so that updated state is some arbitrary function, right?

**Comment by ndmitchell** [comment]
You can overwrite the ovenUpdateState - but be slightly careful. It should be the case that `(s, ps1 ++ ps2)` is roughly equivalent to `(ovenUpdateState s ps1, ps2)` - where equivalent roughly means produces the same code. I'm actually in the middle of rewriting much of Bake to improve lots of things, but one of the fallouts will be that the above law is more "expected" than actually required.

For info, the update will ensure all history is recorded forever (you can see what happened to a patch a week ago) and it will fix #8.

**Comment by abailly** [comment]
Thanks. Having history will be a great plus indeed!

FWIW I have ported our CI to your latest master branch and things are running fine. I of course had to adapt some functions but all in all process was smooth. I especially appreciated the new `Stringy a` class which makes more sense IMHO.

**Comment by ndmitchell** [comment]
Glad to hear you've upgraded to the latest - I'm a few days into the rewrite, so hopefully nearing the end. I suggest you stick at the current latest (which we've been battle testing for quite a while) and hold off moving forward from that for a few more weeks until the rewrite has been tested thoroughly.

**Comment by abailly** [comment]
OK. Thanks for the tip. Anyhow we probably do not have as stringent
requirements as you do :-)

BTW, I met Marten Algren at Haskell meetup in Singapore couple of weeks
ago, and we discussed the motives behind your development of a new CI
engine. Interesting person, and interesting conversation.

-- 
Arnaud Bailly

twitter: abailly
skype: arnaud-bailly
linkedin: http://fr.linkedin.com/in/arnaudbailly/

**Comment by ndmitchell** [comment]
Glad to hear you met Marten. I've just merged the persistent branch which writes everything to sqlite, and am beginning to test it. I'm transitioning at work shortly.
